# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 488a7982554f5dcde728d409ea8f20200dd5e096cfd920b5f397c5d3cb73d1ec28b9083f8bfdd7f2267841503f524430e796a52153e7ab10f4673799d0b0c014

test:
  secret_key_base: b6d85e58fd3b12c6d1d7eb7cbd57980df35b73223bd45b74f18aadc60d5675bce5d349052e9d539419131be4f3ea78668a39f7903a7c070f7572d97a15d549c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
